apiVersion: apps/v1
kind: Deployment
metadata:
  name: voip-backend
  labels:
    app: voip-backend
spec:
  selector:
    matchLabels:
      app: voip-backend
  template:
    metadata:
      labels:
        app: voip-backend
    spec:
      containers:
      - name: voip-backend
        image: sjc.vultrcr.com/voipservices/voip-backend:latest
        ports:
        - containerPort: 8080
